import { useEffect, useState } from 'react';
import { Download, FlaskConical, LoaderCircle, Plus, RefreshCw, ShieldCheck, Trash2, Upload, Users } from 'lucide-react';
import type { AccessRule, LabReport, StudioPreferences, UpdateInfo } from '../shared/studio-types';
import { gatewayModels } from '../shared/gateway-models';
import { useApp } from './context';
import { Field, IconButton, Row, Toggle } from './primitives';
import { CheckSettings } from './Workbench';
import './studio.css';

function LabResults({ report }: { report: LabReport }) {
  const { t } = useApp(); const columns = [...new Set(report.rows.flatMap(row => Object.keys(row)))];
  return <section className="lab-report" aria-live="polite"><p>{report.summary}</p>{report.error && <p className="studio-error">{report.error}</p>}{report.rows.length > 0 && <div className="lab-report-table"><table><thead><tr>{columns.map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{report.rows.map((row, index) => <tr key={index}>{columns.map(column => <td key={column}>{row[column] === null || row[column] === undefined ? t('Not reported', '未报告') : typeof row[column] === 'boolean' ? row[column] ? t('Yes', '是') : t('No', '否') : String(row[column])}</td>)}</tr>)}</tbody></table></div>}</section>;
}

function ModelsLab() {
  const { data, api, run, t } = useApp(); const [selected, setSelected] = useState(''); const [capabilities, setCapabilities] = useState(['text', 'tools', 'reasoning']); const [busy, setBusy] = useState(''); const [report, setReport] = useState<LabReport | null>(null);
  const models = data.gateways.flatMap(gateway => gatewayModels(gateway).map(model => ({ gatewayId: gateway.id, gatewayName: gateway.name, modelId: model.id, label: model.name || model.id, value: JSON.stringify([gateway.id, model.id]) })));
  const current = models.find(model => model.value === selected) || models.find(model => model.gatewayId === data.preferences.defaultGatewayId && model.modelId === data.preferences.defaultModelId) || models[0];
  async function execute(kind: 'capabilities' | 'cache' | 'tasks') { if (!current || busy) return; setBusy(kind); setReport(null); const value = await run(() => kind === 'capabilities' ? api.probeModel(current.gatewayId, current.modelId, capabilities) : kind === 'cache' ? api.benchmarkCache(current.gatewayId, current.modelId) : api.evaluateTasks(current.gatewayId, current.modelId)); if (value) setReport(value); setBusy(''); }
  return <div className="studio-lab"><Field label={t('Model to test', '待测试模型')}><select value={current?.value || ''} onChange={event => setSelected(event.target.value)} disabled={!!busy || !models.length}>{models.length ? data.gateways.map(gateway => <optgroup key={gateway.id} label={gateway.name}>{models.filter(model => model.gatewayId === gateway.id).map(model => <option key={model.value} value={model.value}>{model.label}</option>)}</optgroup>) : <option value="">{t('Configure a gateway first', '请先配置网关')}</option>}</select></Field><div className="lab-capabilities">{[{ id: 'text', label: t('Text', '文本') }, { id: 'tools', label: t('Tools', '工具') }, { id: 'reasoning', label: t('Reasoning', '推理') }, { id: 'image', label: t('Images', '图片') }].map(item => <label className="studio-checkbox" key={item.id}><input type="checkbox" disabled={!!busy} checked={capabilities.includes(item.id)} onChange={event => setCapabilities(current => event.target.checked ? [...current, item.id] : current.filter(value => value !== item.id))} /><span>{item.label}</span></label>)}</div><p className="studio-help">{t('Tests send real requests to the selected model and may incur usage charges. Context capacity remains declared until independently verified.', '测试会向所选模型发送真实请求并产生用量；上下文容量仍以配置值显示。')}</p><div className="studio-button-row"><button className="button small" disabled={!!busy || !current || !capabilities.length} onClick={() => void execute('capabilities')}>{busy === 'capabilities' ? <LoaderCircle size={14} className="spinning" /> : <ShieldCheck size={14} />}{t('Test capabilities', '测试模型能力')}</button><button className="button small" disabled={!!busy || !current} onClick={() => void execute('cache')}>{busy === 'cache' ? <LoaderCircle size={14} className="spinning" /> : <RefreshCw size={14} />}{t('Compare cache', '对比缓存命中')}</button><button className="button small" disabled={!!busy || !current} onClick={() => void execute('tasks')}>{busy === 'tasks' ? <LoaderCircle size={14} className="spinning" /> : <FlaskConical size={14} />}{t('Evaluate real tasks', '真实任务评测')}</button></div>{busy && <p className="studio-loading" role="status">{t('Running; keep this page open…', '正在运行，请保持此页面打开…')}</p>}{report && <LabResults report={report} />}</div>;
}

function AccessRules({ projectId }: { projectId: string }) {
  const { data, api, run, t } = useApp(); const [adding, setAdding] = useState(false); const [kind, setKind] = useState<AccessRule['kind']>('read'); const [scope, setScope] = useState<AccessRule['scope']>('project'); const [taskId, setTaskId] = useState(''); const [target, setTarget] = useState(''); const [saving, setSaving] = useState(false);
  const tasks = data.tasks.filter(task => task.projectId === projectId && !task.archived && !task.parentId); const selectedTaskId = tasks.some(task => task.id === taskId) ? taskId : tasks[0]?.id || ''; const rules = data.studio?.rules.filter(rule => rule.projectId === projectId) || [];
  const kindLabels = { read: t('Read', '读取'), write: t('Write', '写入'), network: t('Network', '网络'), command: t('Command', '命令') };
  async function save() { if (!target.trim()) return; setSaving(true); const ok = await run(async () => { await api.grantRule({ projectId, taskId: scope === 'session' ? selectedTaskId : undefined, scope, kind, target: target.trim() }); return true; }); if (ok) { setTarget(''); setAdding(false); } setSaving(false); }
  return <div><div className="studio-section-heading"><h3>{t('Granted access', '已授予的访问权限')}</h3><button className="button small" disabled={!projectId} onClick={() => setAdding(!adding)}><Plus size={14} />{t('Add rule', '添加规则')}</button></div>{rules.length ? <div className="access-rules">{rules.map(rule => <div key={rule.id}><ShieldCheck size={16} /><span><strong>{kindLabels[rule.kind]} · {rule.target}</strong><small>{rule.scope === 'project' ? t('This project', '当前项目') : `${t('Task', '任务')} · ${data.tasks.find(task => task.id === rule.taskId)?.title || rule.taskId}`}</small></span><IconButton label={`${t('Revoke access', '撤销权限')} ${rule.target}`} onClick={() => void run(() => api.revokeRule(rule.id))}><Trash2 size={15} /></IconButton></div>)}</div> : <p className="studio-empty">{t('No additional permissions have been granted.', '尚未额外授予访问权限。')}</p>}{adding && <form className="access-rule-form" onSubmit={event => { event.preventDefault(); void save(); }}><div className="studio-two-columns"><Field label={t('Access type', '访问类型')}><select value={kind} onChange={event => setKind(event.target.value as AccessRule['kind'])}>{Object.entries(kindLabels).map(([id, title]) => <option value={id} key={id}>{title}</option>)}</select></Field><Field label={t('Applies to', '有效范围')}><select value={scope} onChange={event => setScope(event.target.value as AccessRule['scope'])}><option value="project">{t('This project', '当前项目')}</option><option value="session" disabled={!tasks.length}>{t('One task', '指定任务')}</option></select></Field></div>{scope === 'session' && <Field label={t('Task', '任务')}><select value={selectedTaskId} onChange={event => setTaskId(event.target.value)}>{tasks.map(task => <option value={task.id} key={task.id}>{task.title}</option>)}</select></Field>}<Field label={kind === 'network' ? t('Domain', '域名') : kind === 'command' ? t('Exact command', '完整命令') : t('File or folder path', '文件或目录路径')}><input value={target} onChange={event => setTarget(event.target.value)} placeholder={kind === 'network' ? 'api.example.com' : kind === 'command' ? 'npm test' : 'src'} required /></Field><div className="studio-button-row"><button className="button small" type="button" onClick={() => setAdding(false)}>{t('Cancel', '取消')}</button><button className="button primary small" disabled={saving || !target.trim() || scope === 'session' && !selectedTaskId}>{t('Grant access', '授予权限')}</button></div></form>}</div>;
}

function UpdateSettings() {
  const { data, api, run, t } = useApp(); const [feed, setFeed] = useState(data.studio?.preferences.updateFeed || ''); const [busy, setBusy] = useState(''); const [info, setInfo] = useState<UpdateInfo | null>(null); const [report, setReport] = useState<{ status: string; message: string } | null>(null);
  useEffect(() => setFeed(data.studio?.preferences.updateFeed || ''), [data.studio?.preferences.updateFeed]);
  useEffect(() => { let disposed = false; void api.updateReport().then(value => { if (!disposed) setReport(value || null); }).catch(() => undefined); return () => { disposed = true; }; }, [api]);
  async function action(name: string, callback: () => Promise<UpdateInfo | void>) { setBusy(name); const value = await run(async () => { try { return await callback(); } catch (error) { setInfo({ status: 'failed', message: error instanceof Error ? error.message : String(error) }); throw error; } }); if (value) setInfo(value); setBusy(''); }
  return <div className="studio-updates">{report && ['failed', 'rolled_back'].includes(report.status) && <div className="update-result" role="status"><strong>{report.status === 'rolled_back' ? t('Restored previous version', '已回退到上一版本') : t('Last update failed', '上次更新未完成')}</strong><p className={report.status === 'failed' ? 'studio-error' : ''}>{report.message}</p></div>}<Field label={t('Update feed URL', '更新源地址')}><input type="url" value={feed} placeholder="https://example.com/cardwright/releases.json" onChange={event => setFeed(event.target.value)} onBlur={() => { if (feed !== data.studio?.preferences.updateFeed) void run(() => api.studioSettings({ updateFeed: feed.trim() })); }} /></Field><div className="studio-button-row"><button className="button small" disabled={!!busy || !feed.trim()} onClick={() => void action('check', async () => { await api.studioSettings({ updateFeed: feed.trim() }); return api.checkUpdates(); })}>{busy === 'check' ? <LoaderCircle size={14} className="spinning" /> : <RefreshCw size={14} />}{t('Check updates', '检查更新')}</button><button className="button small" disabled={!!busy} onClick={() => void action('import', () => api.importUpdate())}><Upload size={14} />{t('Import update package', '导入更新包')}</button><button className="text-button" disabled={!!busy} onClick={() => void action('rollback', () => api.rollbackUpdate())}>{t('Restore previous version', '恢复上一版本')}</button></div>{info && <div className="update-result" role="status"><strong>{info.version ? `Cardwright ${info.version}` : t('Update status', '更新状态')}</strong><p className={info.status === 'failed' ? 'studio-error' : ''}>{info.message || info.status}</p>{info.progress !== undefined && <progress max={100} value={info.progress} aria-label={t('Update progress', '更新进度')} />}{['available', 'ready'].includes(info.status) && <button className="button primary small" disabled={!!busy} onClick={() => void action('install', () => api.installUpdate())}><Download size={14} />{busy === 'install' ? t('Preparing…', '准备中…') : t('Install update & restart', '安装更新并重启')}</button>}</div>}</div>;
}

export function StudioSettings() {
  const { data, api, run, t } = useApp(); const studio = data.studio; const [projectId, setProjectId] = useState(data.projects[0]?.id || ''); const project = data.projects.find(project => project.id === projectId) || data.projects[0];
  if (!studio) return <p className="studio-loading">{t('Loading workspace settings…', '正在加载工作区设置…')}</p>;
  const prefs = studio.preferences; const save = (changes: Partial<StudioPreferences>) => void run(() => api.studioSettings(changes));
  const models = data.gateways.flatMap(gateway => gatewayModels(gateway).map(model => ({ gatewayId: gateway.id, modelId: model.id, label: `${gateway.name} / ${model.name || model.id}`, value: JSON.stringify([gateway.id, model.id]) })));
  return <div className="studio-settings-page"><Row title={t('Restricted execution', '受限执行')} description={t('Applies to approved commands. Full access runs directly on the host.', '已批准的命令使用受限环境；完全访问模式直接在本机执行。')}><Toggle label={t('Restricted execution', '受限执行')} checked={prefs.sandboxEnabled} onChange={value => save({ sandboxEnabled: value })} /></Row><Row title={t('Default squad size', '默认小队人数')} description={t('The lead assigns independent work when useful.', '主代理按任务需要分配独立工作。')}><input className="number-input" type="number" min={1} max={6} aria-label={t('Default squad size', '默认小队人数')} value={prefs.defaultSquadSize} onChange={event => { const value = Number(event.target.value); if (value >= 1 && value <= 6) save({ defaultSquadSize: value }); }} /></Row>
    <details className="studio-detail"><summary><Users size={16} />{t('Squad budgets and models', '小队预算与模型')}</summary><div className="studio-three-columns">{([{ key: 'teamTokenBudget', label: t('Token budget', 'Token 预算') }, { key: 'teamMinutesBudget', label: t('Minutes', '时间（分钟）') }, { key: 'teamMoneyBudget', label: t('Cost budget', '金额预算') }] as const).map(item => <Field key={`${item.key}-${prefs[item.key]}`} label={item.label}><input type="number" min={0} step={item.key === 'teamMoneyBudget' ? '0.01' : '1'} defaultValue={prefs[item.key]} onBlur={event => { const value = Number(event.target.value); if (Number.isFinite(value) && value >= 0 && value !== prefs[item.key]) save({ [item.key]: value }); }} /></Field>)}</div><p className="studio-help">{t('0 means unlimited. Set model prices before using a cost limit.', '0 表示不设上限；金额预算需要先配置模型单价。')}</p><div className="role-model-settings">{data.ecosystem.roles.map(role => { const configured = prefs.roleModels[role.id]; return <div key={role.id}><strong>{role.name}</strong><select aria-label={`${role.name} ${t('model', '模型')}`} value={configured ? JSON.stringify([configured.gatewayId, configured.modelId]) : ''} onChange={event => { const next = { ...prefs.roleModels }; if (!event.target.value) delete next[role.id]; else { const [gatewayId, modelId] = JSON.parse(event.target.value) as string[]; next[role.id] = { gatewayId, modelId, thinking: configured?.thinking || 'medium' }; } save({ roleModels: next }); }}><option value="">{t('Inherit lead model', '跟随主代理模型')}</option>{models.map(model => <option key={model.value} value={model.value}>{model.label}</option>)}</select>{configured && <select aria-label={`${role.name} ${t('effort', '强度')}`} value={configured.thinking} onChange={event => save({ roleModels: { ...prefs.roleModels, [role.id]: { ...configured, thinking: event.target.value } } })}>{['low', 'medium', 'high', 'xhigh', 'max'].map(level => <option key={level} value={level}>{level}</option>)}</select>}</div>; })}</div></details>
    <details className="studio-detail"><summary><ShieldCheck size={16} />{t('Project checks and access', '项目检查与权限')}</summary>{project ? <><Field label={t('Project', '项目')}><select value={project.id} onChange={event => setProjectId(event.target.value)}>{data.projects.map(project => <option value={project.id} key={project.id}>{project.name}</option>)}</select></Field><CheckSettings key={`checks-${project.id}`} projectId={project.id} /><AccessRules key={`rules-${project.id}`} projectId={project.id} /></> : <p className="studio-empty">{t('Add a project to configure checks and permissions.', '添加项目后可配置检查与权限。')}</p>}</details>
    <details className="studio-detail"><summary><FlaskConical size={16} />{t('Model diagnostics', '模型验证与评测')}</summary><ModelsLab /></details>
    <details className="studio-detail"><summary><Download size={16} />{t('Updates and recovery', '更新与恢复')}</summary><UpdateSettings /></details>
  </div>;
}
